import { Button } from '@mui/material'
import { signInWithPopup } from 'firebase/auth'
import Head from 'next/head'
import styled from 'styled-components'
import { auth, provider } from '../firebase'
import CircularProgress from '@mui/material/CircularProgress'

const Login = ({ loading }) => {
  const handleSignIn = () => {
    signInWithPopup(auth, provider).catch(alert)
  }

  return (
    <Container>
      <Head>
        <title>WhatsApp - Login</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link
          rel='icon'
          href='https://assets.stickpng.com/images/580b57fcd9996e24bc43c543.png'
        />
        <meta name='referrer' content='no-referrer' />
      </Head>

      <LoginContainer>
        {loading ? (
          <CircularProgress color='success' />
        ) : (
          <>
            <LogoImg
              src='https://assets.stickpng.com/images/580b57fcd9996e24bc43c543.png'
              alt='WhatsApp logo'
            />
            <SignInButton
              loading={loading}
              onClick={handleSignIn}
              variant='outlined'
            >
              Sign in with Google
            </SignInButton>
          </>
        )}
      </LoginContainer>
    </Container>
  )
}

export default Login

const Container = styled.div`
  background: url('./loginBackground.png') no-repeat;
  display: grid;
  place-items: center;
  height: 100vh;
`

const LoginContainer = styled.main`
  display: flex;
  flex-direction: column;
  background-color: whitesmoke;
  padding: 50px;
  align-items: center;
  gap: 30px;
  border-radius: 5px;
  box-shadow: 0 4px 14px -3px #002101;
`
const LogoImg = styled.img`
  object-fit: cover;
  width: 200px;
  height: 200px;
  @media (min-width: 640px) {
    width: 250px;
    height: 250px;
  }
`

const SignInButton = styled(Button)`
  color: darkgreen;
  font-weight: bold;
  border-color: darkgreen;
  &:hover {
    border-color: green;
    background-color: #acedac;
  }
`
