import { Button } from '@mui/material'
import { signInWithPopup } from 'firebase/auth'
import Head from 'next/head'
import styled from 'styled-components'
import { auth, provider } from '../firebase'
import CircularProgress from '@mui/material/CircularProgress'
import Image from 'next/image'
import logoImg from '../public/logo.webp'

const Login = ({ loading }) => {
  const handleSignIn = () => {
    signInWithPopup(auth, provider).catch(alert)
  }

  return (
    <Container
      style={{
        display: 'grid',
        placeItems: 'center',
        height: '100vh',
        background: 'url(/background.webp) no-repeat',
        backgroundSize: 'cover',
      }}
    >
      <Head>
        <title>WhatsApp - Login</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/logo.webp' />
        <meta name='referrer' content='no-referrer' />
      </Head>

      <LoginContainer
        style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          padding: '50px',
          backgroundColor: '#111b21',
          gap: '30px',
        }}
      >
        <LogoImg src={logoImg} width={250} height={250} alt='WhatsApp logo' />
        {loading ? (
          <CircularProgress color='success' />
        ) : (
          <>
            <SignInButton
              loading={loading}
              onClick={handleSignIn}
              variant='outlined'
            >
              Sign in with Google
            </SignInButton>
          </>
        )}
      </LoginContainer>
    </Container>
  )
}

export default Login

const Container = styled.div``

const LoginContainer = styled.main`
  border-radius: 5px;
  box-shadow: 0 4px 14px -3px #111b21;
`

const LogoImg = styled(Image)`
  object-fit: contain;
  width: 200px;
  height: 200px;
  @media (min-width: 640px) {
    width: 250px;
    height: 250px;
  }
`

const SignInButton = styled(Button)`
  color: #aebac1;
  font-weight: 700;
  border-color: #aebac1;
  &:hover {
    border-color: #8696a0;
    background-color: #8696a0;
    color: #111b21;
  }
`
