import Head from 'next/head'
import '../styles/globals.css'
import { useAuthState } from 'react-firebase-hooks/auth'
import { auth, db } from '../firebase'
import LoginPage from './login'
import { useEffect, useState } from 'react'
import {
  doc,
  getDoc,
  serverTimestamp,
  setDoc,
  updateDoc,
} from 'firebase/firestore'
import { Roboto } from '@next/font/google'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
})
export default function App({ Component, pageProps }) {
  const [user, loading] = useAuthState(auth)
  const [loadApp, setLoadApp] = useState(true)

  const setUserStatus = async () => {
    if (user.providerData[0].providerId === 'google.com') {
      await setDoc(doc(db, 'users', auth.currentUser.uid), {
        email: auth.currentUser.email,
        name: auth.currentUser.displayName,
        userImg: auth.currentUser.photoURL,
        lastSeen: serverTimestamp(),
      })
    }
    if (user.providerData[0].providerId === 'phone') {
      await updateDoc(doc(db, 'users', auth.currentUser.uid), {
        lastSeen: serverTimestamp(),
      })
    }
  }
  useEffect(() => {
    if (user) {
      setUserStatus()
    } else if (loading) {
      setLoadApp(true)
    } else {
      console.log('false load app')
      setLoadApp(false)
    }
  }, [user])

  if (loading) return <LoginPage loading />
  if (!user || !loadApp) return <LoginPage setLoadApp={setLoadApp} />

  return (
    <main className={roboto.className}>
      <Head>
        <title>WhatsApp</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='./logo.webp' />
        <meta name='referrer' content='no-referrer' />
      </Head>

      <Component {...pageProps} />
    </main>
  )
}
