import Head from 'next/head'
import '../styles/globals.css'
import { useAuthState } from 'react-firebase-hooks/auth'
import { auth, db } from '../firebase'
import LoginPage from './login'
import { useEffect } from 'react'
import { doc, serverTimestamp, setDoc } from 'firebase/firestore'
import { Roboto } from '@next/font/google'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
})
export default function App({ Component, pageProps }) {
  const [user, loading] = useAuthState(auth)

  const setUserStatus = async () => {
    await setDoc(doc(db, 'users', auth.currentUser.uid), {
      email: auth.currentUser.email,
      name: auth.currentUser.displayName,
      userImg: auth.currentUser.photoURL,
      lastSeen: serverTimestamp(),
    })
  }
  useEffect(() => {
    if (user) {
      setUserStatus()
    }
  }, [user])

  if (loading) return <LoginPage loading />
  if (!user) return <LoginPage />
  return (
    <main className={roboto.className}>
      <Head>
        <title>WhatsApp</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='./logo.webp' />
        <meta name='referrer' content='no-referrer' />
      </Head>

      <Component {...pageProps} />
    </main>
  )
}
